# Generated by Django 4.0.6 on 2022-07-28 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=999, verbose_name='email')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='date')),
            ],
        ),
    ]
