# Generated by Django 4.0.6 on 2022-07-30 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='sms_password',
            field=models.CharField(blank=True, max_length=999, null=True, verbose_name='sms password'),
        ),
        migrations.AddField(
            model_name='settings',
            name='sms_phone',
            field=models.CharField(blank=True, max_length=999, null=True, verbose_name='sms phone'),
        ),
        migrations.AddField(
            model_name='settings',
            name='sms_username',
            field=models.CharField(blank=True, max_length=999, null=True, verbose_name='sms username'),
        ),
    ]
