# Generated by Django 4.0.6 on 2022-07-28 07:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tikets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False, verbose_name='status')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='date')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_db', to=settings.AUTH_USER_MODEL, verbose_name='customer')),
                ('support', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='support')),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True, verbose_name='text')),
                ('file', models.FileField(blank=True, null=True, upload_to='filesMessages', verbose_name='file')),
                ('role', models.CharField(blank=True, choices=[('support', 'support'), ('customer', 'customer')], max_length=60, null=True, verbose_name='role')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='date')),
                ('tiket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.tikets', verbose_name='tiket')),
            ],
        ),
    ]
