# Generated by Django 4.0.6 on 2022-07-25 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usersmodel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userperson',
            name='phone_auth',
        ),
    ]
