# Generated by Django 4.0.6 on 2022-07-29 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_carts_payment_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=999, verbose_name='code')),
                ('status', models.CharField(max_length=999, verbose_name='status')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.carts', verbose_name='cart')),
            ],
        ),
    ]
