# Generated by Django 4.0.6 on 2022-07-29 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_producttracking'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductTracking',
            new_name='Trackings',
        ),
    ]
