# Generated by Django 4.0.6 on 2022-07-29 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_rename_producttracking_trackings'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='tracking_code',
            field=models.CharField(blank=True, max_length=999, null=True, verbose_name='tracking code'),
        ),
    ]
